# DW_pandas_Task1

## 20201214

### 写在学习时
跟随DataWhale的组队学习Pandas，在第一章就卡壳了，基础过于薄弱，学起来很困难，看看好象都是懂了，用却用不出来，努力把进度学完，掌握不好以后再持续学习。
资料结合视频在看，练习看了视频再自己揣摩，不能完成，还是依靠参考答案了：（

## 练习
### Ex1：利用列表推导式写矩阵乘法
一般的矩阵乘法根据公式，可以由三重循环写出，请将其改写为列表推导式的形式。

In [3]:
import numpy as np
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
((M1@M2 - res) < 1e-15).all() # 排除数值误差

True

列表推导式，看了视频后明白大概的道理，百度资料

第一种是：[ 表达式 外层的for 循环语句的第一行 内层for 循环语句的第一行]
外循环在前，内循环在后。

第二种是：[ [表达式 内层的for 循环语句的第一行] 外层for 循环语句的第一行]
显然是列表套列表；把内层循环在前做为表达式来使用，外层循环再后。

还是没学会，参考答案试着理解

In [4]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = [[sum([M1[i][k]*M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])]for i in range(M1.shape[0])]
((M1@M2 - res) < 1e-15).all()

True

### Ex2：更新矩阵
设矩阵 $A_{m×n}$ ，现在对 $A$ 中的每一个元素进行更新生成矩阵 $B$ ，更新方法是 $B_{ij}=A_{ij}\sum_{k=1}^n\frac{1}{A_{ik}}$ ，例如下面的矩阵为 $A$ ，则 $B_{2,2}=5\times(\frac{1}{4}+\frac{1}{5}+\frac{1}{6})=\frac{37}{12}$ ，请利用 `Numpy` 高效实现。
$$\begin{split}A=\left[ \begin{matrix} 1 & 2 &3\\4&5&6\\7&8&9 \end{matrix} \right]\end{split}$$

In [5]:
a = np.arange(1,10).reshape(3,-1)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b = 1/a
b

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [7]:
a*(1/a).sum(1).reshape(-1,1)

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])

这个reshape(-1,1)的转换还没弄明白？还有加不加括号没区别啊。

### Ex3：卡方统计量

设矩阵$A_{m\times n}$，记$B_{ij} = \frac{(\sum_{i=1}^mA_{ij})\times (\sum_{j=1}^nA_{ij})}{\sum_{i=1}^m\sum_{i=1}^nA_{ij}}$，定义卡方值如下：
$$\chi^2 = \sum_{i=1}^m\sum_{j=1}^n\frac{(A_{ij}-B_{ij})^2}{B_{ij}}$$
请利用`Numpy`对给定的矩阵$A$计算$\chi^2$ 

In [8]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))
A

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11]])

这个公式直接就没看懂。
看视频，B公式是（列求和+行求和）/A求和

In [9]:
B = A.sum(0)*(A.sum(1).reshape(-1,1))/A.sum()
B

array([[14.14211438, 13.08145581, 15.20277296, 13.67071057, 11.90294627],
       [15.18197574, 14.04332756, 16.32062392, 14.67590988, 12.77816291],
       [16.63778163, 15.38994801, 17.88561525, 16.08318891, 14.0034662 ],
       [16.42980936, 15.19757366, 17.66204506, 15.88214905, 13.82842288],
       [17.67764298, 16.35181976, 19.0034662 , 17.08838821, 14.87868284],
       [12.68630849, 11.73483536, 13.63778163, 12.26343154, 10.67764298],
       [13.93414211, 12.88908146, 14.97920277, 13.46967071, 11.72790295],
       [13.3102253 , 12.31195841, 14.3084922 , 12.86655113, 11.20277296]])

这里又有reshape转置的问题，空间感不强，脑子不够用

In [10]:
((A-B)**2/B).sum()

11.842696601945802

听了讲解，分开做还是能懂一点，多学学多做做吧

### Ex4：改进矩阵计算的性能
设$Z$为$m×n$的矩阵，$B$和$U$分别是$m×p$和$p×n$的矩阵，$B_i$为$B$的第$i$行，$U_j$为$U$的第$j$列，下面定义$\displaystyle R=\sum_{i=1}^m\sum_{j=1}^n\|B_i-U_j\|_2^2Z_{ij}$，其中$\|\mathbf{a}\|_2^2$表示向量$a$的分量平方和$\sum_i a_i^2$。

现有某人根据如下给定的样例数据计算$R$的值，请充分利用`Numpy`中的函数，基于此问题改进这段代码的性能。

In [11]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i]-U[:,j])**2).sum()
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)
solution(B, U, Z)

100566

In [12]:
(((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) -2*B@U)*Z).sum()

100566

In [13]:
%timeit -n 30 solution(B, U, Z)

35 ms ± 331 µs per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [14]:
%timeit -n 30 ((np.ones((m,n))*(B**2).sum(1).reshape(-1,1)+\
               np.ones((m,n))*(U**2).sum(0) - 2*B@U)*Z).sum()

530 µs ± 61.1 µs per loop (mean ± std. dev. of 7 runs, 30 loops each)


性能优化完全不懂，参照视频的分解公式还能明白一些，嗯，我想多做就能OK的。
好象对reshape(-1,1)有那么点感觉了，哈！

### Ex5：连续整数的最大长度

输入一个整数的`Numpy`数组，返回其中递增连续整数子数组的最大长度，正向是指递增方向。例如，输入\[1,2,5,6,7\]，\[5,6,7\]为具有最大长度的连续整数子数组，因此输出3；输入\[3,2,1,2,3,4,6\]，\[1,2,3,4\]为具有最大长度的连续整数子数组，因此输出4。请充分利用`Numpy`的内置函数完成。（提示：考虑使用`nonzero, diff`函数）

In [15]:
x = np.array([1,2,5,6,7])
np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()

3

In [16]:
np.r_[1,np.diff(x)!=1,1]

array([1, 0, 1, 0, 0, 1], dtype=int32)

In [18]:
np.diff(x)!=1,1

(array([False,  True, False, False]), 1)

In [21]:
np.nonzero(np.r_[1,np.diff(x)!=1,1])

(array([0, 2, 5], dtype=int64),)

In [22]:
np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1]))

array([[2, 3]], dtype=int64)

不懂它，就一步步分解，解题思路需要慢慢培养。

### 题后话
我总是认为，没有学不会的东西，虽然现在很难，或许以后也不一定学会，但我想做人还是要努力一把，不管如何，尽力跟上。
28天的课程，努力打完卡，先囫囵吞枣，再慢慢消化。
又，年底单位工作较忙，精力有限，时间上不好安排，只能是匆忙打卡，并非不想好好消化，所欠的，以后再补。